
package Gens.verdun;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VerdunTheatreService", targetNamespace = "http://Verdun.servers/", wsdlLocation = "http://localhost:8888/verdun?wsdl")
public class VerdunTheatreService
    extends Service
{

    private final static URL VERDUNTHEATRESERVICE_WSDL_LOCATION;
    private final static WebServiceException VERDUNTHEATRESERVICE_EXCEPTION;
    private final static QName VERDUNTHEATRESERVICE_QNAME = new QName("http://Verdun.servers/", "VerdunTheatreService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/verdun?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VERDUNTHEATRESERVICE_WSDL_LOCATION = url;
        VERDUNTHEATRESERVICE_EXCEPTION = e;
    }

    public VerdunTheatreService() {
        super(__getWsdlLocation(), VERDUNTHEATRESERVICE_QNAME);
    }

    public VerdunTheatreService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VERDUNTHEATRESERVICE_QNAME, features);
    }

    public VerdunTheatreService(URL wsdlLocation) {
        super(wsdlLocation, VERDUNTHEATRESERVICE_QNAME);
    }

    public VerdunTheatreService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VERDUNTHEATRESERVICE_QNAME, features);
    }

    public VerdunTheatreService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerdunTheatreService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VerdunTheatre
     */
    @WebEndpoint(name = "VerdunTheatrePort")
    public VerdunTheatre getVerdunTheatrePort() {
        return super.getPort(new QName("http://Verdun.servers/", "VerdunTheatrePort"), VerdunTheatre.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerdunTheatre
     */
    @WebEndpoint(name = "VerdunTheatrePort")
    public VerdunTheatre getVerdunTheatrePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Verdun.servers/", "VerdunTheatrePort"), VerdunTheatre.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VERDUNTHEATRESERVICE_EXCEPTION!= null) {
            throw VERDUNTHEATRESERVICE_EXCEPTION;
        }
        return VERDUNTHEATRESERVICE_WSDL_LOCATION;
    }

}
