
package Gens.verdun;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VerdunTheatre", targetNamespace = "http://Verdun.servers/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VerdunTheatre {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "addTestData", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddTestData")
    @ResponseWrapper(localName = "addTestDataResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddTestDataResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/addTestDataRequest", output = "http://Verdun.servers/VerdunTheatre/addTestDataResponse")
    public void addTestData();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listMovieShowsAvailability", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.ListMovieShowsAvailability")
    @ResponseWrapper(localName = "listMovieShowsAvailabilityResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.ListMovieShowsAvailabilityResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/listMovieShowsAvailabilityRequest", output = "http://Verdun.servers/VerdunTheatre/listMovieShowsAvailabilityResponse")
    public String listMovieShowsAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookMovieTickets", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.BookMovieTickets")
    @ResponseWrapper(localName = "bookMovieTicketsResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.BookMovieTicketsResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/bookMovieTicketsRequest", output = "http://Verdun.servers/VerdunTheatre/bookMovieTicketsResponse")
    public String bookMovieTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "exchangeTickets", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.ExchangeTickets")
    @ResponseWrapper(localName = "exchangeTicketsResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.ExchangeTicketsResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/exchangeTicketsRequest", output = "http://Verdun.servers/VerdunTheatre/exchangeTicketsResponse")
    public String exchangeTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        int arg5);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeMovieSlots", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.RemoveMovieSlots")
    @ResponseWrapper(localName = "removeMovieSlotsResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.RemoveMovieSlotsResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/removeMovieSlotsRequest", output = "http://Verdun.servers/VerdunTheatre/removeMovieSlotsResponse")
    public String removeMovieSlots(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMovieSlots", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddMovieSlots")
    @ResponseWrapper(localName = "addMovieSlotsResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddMovieSlotsResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/addMovieSlotsRequest", output = "http://Verdun.servers/VerdunTheatre/addMovieSlotsResponse")
    public String addMovieSlots(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "updateMovieCount", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.UpdateMovieCount")
    @ResponseWrapper(localName = "updateMovieCountResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.UpdateMovieCountResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/updateMovieCountRequest", output = "http://Verdun.servers/VerdunTheatre/updateMovieCountResponse")
    public void updateMovieCount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        boolean arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCustomerMovieCount", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddCustomerMovieCount")
    @ResponseWrapper(localName = "addCustomerMovieCountResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddCustomerMovieCountResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/addCustomerMovieCountRequest", output = "http://Verdun.servers/VerdunTheatre/addCustomerMovieCountResponse")
    public void addCustomerMovieCount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "findCustomersAndAdjustTimings", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.FindCustomersAndAdjustTimings")
    @ResponseWrapper(localName = "findCustomersAndAdjustTimingsResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.FindCustomersAndAdjustTimingsResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/findCustomersAndAdjustTimingsRequest", output = "http://Verdun.servers/VerdunTheatre/findCustomersAndAdjustTimingsResponse")
    public void findCustomersAndAdjustTimings(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkBookingExists", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.CheckBookingExists")
    @ResponseWrapper(localName = "checkBookingExistsResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.CheckBookingExistsResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/checkBookingExistsRequest", output = "http://Verdun.servers/VerdunTheatre/checkBookingExistsResponse")
    public boolean checkBookingExists(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cancelMovieTickets", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.CancelMovieTickets")
    @ResponseWrapper(localName = "cancelMovieTicketsResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.CancelMovieTicketsResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/cancelMovieTicketsRequest", output = "http://Verdun.servers/VerdunTheatre/cancelMovieTicketsResponse")
    public String cancelMovieTickets(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addMovieSlotInHashMap", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddMovieSlotInHashMap")
    @ResponseWrapper(localName = "addMovieSlotInHashMapResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.AddMovieSlotInHashMapResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/addMovieSlotInHashMapRequest", output = "http://Verdun.servers/VerdunTheatre/addMovieSlotInHashMapResponse")
    public boolean addMovieSlotInHashMap(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "bookMovieTicketsInLocalServer", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.BookMovieTicketsInLocalServer")
    @ResponseWrapper(localName = "bookMovieTicketsInLocalServerResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.BookMovieTicketsInLocalServerResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/bookMovieTicketsInLocalServerRequest", output = "http://Verdun.servers/VerdunTheatre/bookMovieTicketsInLocalServerResponse")
    public String bookMovieTicketsInLocalServer(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getLocalMoviesShowsAvailability", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.GetLocalMoviesShowsAvailability")
    @ResponseWrapper(localName = "getLocalMoviesShowsAvailabilityResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.GetLocalMoviesShowsAvailabilityResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/getLocalMoviesShowsAvailabilityRequest", output = "http://Verdun.servers/VerdunTheatre/getLocalMoviesShowsAvailabilityResponse")
    public String getLocalMoviesShowsAvailability(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingSchedule", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.GetBookingSchedule")
    @ResponseWrapper(localName = "getBookingScheduleResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.GetBookingScheduleResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/getBookingScheduleRequest", output = "http://Verdun.servers/VerdunTheatre/getBookingScheduleResponse")
    public String getBookingSchedule(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCountOfTicketFromOtherTheatres", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.GetCountOfTicketFromOtherTheatres")
    @ResponseWrapper(localName = "getCountOfTicketFromOtherTheatresResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.GetCountOfTicketFromOtherTheatresResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/getCountOfTicketFromOtherTheatresRequest", output = "http://Verdun.servers/VerdunTheatre/getCountOfTicketFromOtherTheatresResponse")
    public int getCountOfTicketFromOtherTheatres(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "findNextAvailableSlotAndReturnSlot", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.FindNextAvailableSlotAndReturnSlot")
    @ResponseWrapper(localName = "findNextAvailableSlotAndReturnSlotResponse", targetNamespace = "http://Verdun.servers/", className = "Gens.verdun.FindNextAvailableSlotAndReturnSlotResponse")
    @Action(input = "http://Verdun.servers/VerdunTheatre/findNextAvailableSlotAndReturnSlotRequest", output = "http://Verdun.servers/VerdunTheatre/findNextAvailableSlotAndReturnSlotResponse")
    public void findNextAvailableSlotAndReturnSlot(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

}
